### ISSUE TITLE
No module named 'selenium' zap-full-scan.py with auth_hook.py

### ISSUE THREAD

**Issue by hamzaElharti** [ICTU/zap2docker-auth-weekly#48]
Hello, 
When running a scan with auth_hook I get an error: 

> docker command:

`docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-full-scan.py -I -j -m 10 -T 60 \
  -t http://localhost:3000 \
  -r testreport.html \
  --hook=/zap/auth_hook.py \
  -z "auth.loginurl=http://localhost:3000/#/login \
      auth.username="demo" \
      auth.password="demo" \
      auth.username_field="email" \
      auth.password_field="password" \
      auth.submit_field="loginButton"" \`

> The output:

Traceback (most recent call last):
  File "/zap/zap-full-scan.py", line 520, in <module>
    main(sys.argv[1:])
  File "/zap/zap-full-scan.py", line 214, in main
    load_custom_hooks(hook_file)
  File "/zap/zap_common.py", line 84, in load_custom_hooks
    loader.exec_module(hooks_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/zap/auth_hook.py", line 1, in <module>
    import zap_auth
  File "/zap/zap_auth.py", line 10, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by hamzaElharti** [comment]
Very kind reminder.

Hamza

**Comment by dicksnel** [comment]
Did you pull the latest version? I cannot reproduce the issue.

**Comment by hamzaElharti** [comment]
> Did you pull the latest version? I cannot reproduce the issue.

Yes, I use the latest version and run it with podman.

**Comment by erno1978** [comment]
Hello @hamzaElharti We are currently reviewing if there's still a usecase for this repository because in the meanwhile, ZAP seems to have included the same functionality. Do you (still) have a specific reason to use this repostory instead of the "original ZAP"?

Sorry, it's been a while before you got this answer.
