### ISSUE TITLE
chromedriver version

### ISSUE THREAD

**Issue by megane-ssi** [ICTU/zap2docker-auth-weekly#53]
I get this error message while runing a scan api with ajax option :
*******
 File "/zap/zap_auth.py", line 80, in authenticate
    self.setup_webdriver()
  File "/zap/zap_auth.py", line 67, in setup_webdriver
    self.driver = webdriver.Chrome(options=options)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 103.0.5060.134 with binary path /usr/bin/google-chrome
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 103.0.5060.134 with binary path /usr/bin/google-chrome
*******
I tried upgrading chromedriver in the image but I have no prmission what is the solution plz?

**Comment by bat79a** [comment]
+1 ;(

My logs

```
Traceback (most recent call last):
  File "/zap/zap_auth.py", line 80, in authenticate
    self.setup_webdriver()
  File "/zap/zap_auth.py", line 67, in setup_webdriver
    self.driver = webdriver.Chrome(options=options)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zap/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 100
Current browser version is 105.0.5195.102 with binary path /usr/bin/google-chrome
```

**Comment by dicksnel** [comment]
@bat79a I just commited a fix. Can you try again after the image is ready on Docker Hub?

**Comment by bat79a** [comment]
@dicksnel 
YES Perfect, thx a lot for this quick fix.
Have a good day, and thx again.
