### ISSUE TITLE
Auth Bearer cached in the first run and not being updated during successive runs

### ISSUE THREAD

**Issue by rdocchio** [ICTU/zap2docker-auth-weekly#66]
Hello

i'm facing an issue using the ictu/zap2docker-auth-weekly while using the auth.bearer_token option.

I'm running a docker container with the zap2docker image 

Docker command:
`docker run -it -v --rm -v $(pwd):/zap/wrk/:rw ictu/zap2docker-weekly:latest bash
`
Command
`zap@046219a21fb2:/zap$ zap-api-scan.py -t "${hostname}${path}" -r endpoint$(echo "$path" | tr '/' '_').html --hook=/zap/auth_hook.py -f openapi -z "auth.bearer_token=$ACCESS_TOKEN"`

The first time i set the ACCESS_TOKEN Env Var it runs correctly, getting HTTP status code 200 for the endpoint

But after the first run, when i set a different ACCESS_TOKEN in the STDOUT appears the new access token 

![image](https://github.com/ICTU/zap2docker-auth-weekly/assets/124214521/62a645ed-edf1-443a-83d9-e8a46dd57d2f)

But if i sniff the packets for the requests the authorization headers appears the first ACCESS_TOKEN that i have set in the first run

![image](https://github.com/ICTU/zap2docker-auth-weekly/assets/124214521/be9e6714-1a5f-4700-a7a9-13e43e377cf5)

Is there a way to do a clean run for the command?

The way i want to implement it is running it within a CI/CD Pipeline job, i will get the open-api specification for the application and iterate over the endpoints that it exposes. I want to be able to get a new Access token before testing the endpoint.

Can you help me with this?

Thanks in advance

**Comment by rdocchio** [comment]
Adding some info about the issue, in the zap.out file for the second run i get the following message

7975 [ZAP-IO-Server-1-1] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/replacer/action/addRule/] from [127.0.0.1]:
org.zaproxy.zap.extension.api.ApiException: already_exists
        at org.zaproxy.zap.extension.replacer.ReplacerAPI.handleApiAction(ReplacerAPI.java:116) ~[?:?]
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:521) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:100) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:74) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:59) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
8230 [ZAP-IO-Server-1-1] WARN  org.zaproxy.zap.extension.api.API - Bad request to API endpoint [/JSON/replacer/action/addRule/] from [127.0.0.1]:
org.zaproxy.zap.extension.api.ApiException: already_exists
        at org.zaproxy.zap.extension.replacer.ReplacerAPI.handleApiAction(ReplacerAPI.java:116) ~[?:?]
        at org.zaproxy.zap.extension.api.API.handleApiRequest(API.java:521) ~[zap-2.12.0.jar:2.12.0]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleApiRequest(ZapApiHandler.java:100) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleRequest(ZapApiHandler.java:74) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.handlers.ZapApiHandler.handleMessage(ZapApiHandler.java:59) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.notifyMessageHandlers(MainServerHandler.java:151) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.processMessage(MainServerHandler.java:131) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.LocalServerHandler.processMessage(LocalServerHandler.java:67) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.process(MainServerHandler.java:94) ~[?:?]
        at org.zaproxy.addon.network.internal.server.http.MainServerHandler.lambda$channelRead0$0(MainServerHandler.java:82) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
11030 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Failed to parse OpenAPI definition.

org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Failed to parse swagger defn null
11030 [ZAP-Import-OpenAPI-1] WARN  org.zaproxy.zap.extension.openapi.ExtensionOpenApi - Failed to parse swagger defn null
org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerException: Failed to parse swagger defn null
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.readOpenAPISpec(SwaggerConverter.java:205) ~[?:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getOperationModels(SwaggerConverter.java:183) ~[?:?]
        at org.zaproxy.zap.extension.openapi.converter.swagger.SwaggerConverter.getRequestModels(SwaggerConverter.java:190) ~[?:?]
        at org.zaproxy.zap.extension.openapi.ExtensionOpenApi$1.run(ExtensionOpenApi.java:409) ~[?:?]

**Comment by rdocchio** [comment]
As a Workaround I was able to solve it by executing the following command before running a second scan 

`sed -i "s@<replacement>Bearer .*</replacement>@<replacement>Bearer $ACCESS_TOKEN</replacement>@" /home/zap/.ZAP/config.xml`

it would be nice if zap can update it automatically

**Comment by dicksnel** [comment]
Hi @rdocchio, do you mean you run another scan in the same container? Or do you start a new container? I don't think you can change the env var after the container is running. You could just run a new container for each scan:

```
docker run -it -v --rm -v $(pwd):/zap/wrk/:rw ictu/zap2docker-weekly:latest  zap-api-scan.py -t "${hostname}${path}" -r endpoint$(echo "$path" | tr '/' '_').html --hook=/zap/auth_hook.py -f openapi -z "auth.bearer_token=$ACCESS_TOKEN"
```
